### ISSUE TITLE
Log the invalid header value in case of "400 Bad Request: invalid header value"

### ISSUE THREAD

**Issue by shilpa24balaji** [xmidt-org/petasos#23]
Observing this 400 error in parodus client and there are many instances of this error in field. 

https://splunk.ccp.cable.comcast.com/en-US/app/search/search?q=search%20SYS_ERROR_Parodus_http400%20index%3Drdk-json%20%7C%20stats%20count%20by%20searchResult%7B%7D.mac&display.page.search.mode=smart&dispatch.sample_ratio=1&earliest=-15m&latest=now&display.statistics.sortColumn=count&display.statistics.sortDirection=desc&sid=1536368013.619768_09B47B20-7D32-48EB-9C39-FC9836F25DDE&display.page.search.tab=statistics&display.general.type=statistics

```
180908-01:15:24.784050 [mod=PARODUS, lvl=INFO] [tid=3604] PARODUS: nopoll_conn.c:285 IPv4 address of fabric.xmidt.comcast.net is 96.116.57.120  
180908-01:15:26.564083 [mod=PARODUS, lvl=ERROR] [tid=3604] PARODUS: nopoll_conn.c:2955 websocket server denied connection with: 400 Bad Request: invalid header value 
180908-01:15:26.564083 [mod=PARODUS, lvl=INFO] [tid=3604] PARODUS: nopoll_conn.c:2962 Received HTTP 400 response from server 
180908-01:15:26.564083 [mod=PARODUS, lvl=INFO] [tid=3604] PARODUS: nopoll_conn.c:2964 conn->handshake->httpStatus: 400 
180908-01:15:26.574083 [mod=PARODUS, lvl=ERROR] [tid=3604] PARODUS: nopoll_conn.c:2802 Received uncomplete listener handshake reply ((nil) 0 1) 
180908-01:15:26.574083 [mod=PARODUS, lvl=INFO] [tid=3604] PARODUS: nopoll_conn.c:5033 nopoll_conn_wait_until_connection_ready() response: status: 400 
180908-01:15:26.574083 [mod=PARODUS, lvl=ERROR] [tid=3604] PARODUS: Client connection timeout
180908-01:15:26.574083 [mod=PARODUS, lvl=ERROR] [tid=3604] PARODUS: RDK-10037 - WebPA Connection Lost
```

To get to the root cause of this issue please log the invalid header value in petasos logs.

**Comment by githubsands** [comment]
@shilpa24balaji hacking at this now.

**Comment by joe94** [comment]
Fixed in https://github.com/xmidt-org/petasos/pull/30
