### ISSUE TITLE
Petasos may have incorrect sd counts

### ISSUE THREAD

**Issue by johnabass** [xmidt-org/petasos#53]
The issues we've seen with talaria may be affecting petasos.  We really need to create a new chart that shows all the petasos SD counts, the same as we already have with talaria.

**Comment by johnabass** [comment]
There's already a chart that shows petasos's sd counts:
https://metrics.xmidt.comcast.net/d/000000019/petasos-info?orgId=1&refresh=1m

So, we need to monitor and verify that petasos doesn't have the same issue.

**Comment by mykllterry** [comment]
I've made a new dashboard that shows all the current SD metrics in one place: https://metrics.xmidt.comcast.net/d/iXopg_nGk/service-discovery-all-servers?orgId=1
