### ISSUE TITLE
Add optional OpenTelemetry tracing

### ISSUE THREAD

**Issue by joe94** [xmidt-org/petasos#68]
We should try and stay consistent with how the feature is configured and set up. Here's an example from Tr1d1um: https://github.com/xmidt-org/tr1d1um/issues/203

**Comment by utsavbatra5** [comment]
Hi Joe, There is no use of mux.Router in petasos. How do we plan to inject the trace middleware? I was working on a PR for petasos Otel tracing.

**Comment by utsavbatra5** [comment]
PR https://github.com/xmidt-org/petasos/pull/67 opened for the same.

**Comment by Sachin4403** [comment]
Hi @joe94,
Could you mark this as in-progress on this https://github.com/orgs/xmidt-org/projects/6
